version: '3.1'
services:
  db:
    image: postgres:9.4
    container_name: postgres_service_order
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
